### ISSUE TITLE
Two-factor Authentication not working on PGSQL

### ISSUE THREAD

**Issue by shinshadows** [rappasoft/laravel-boilerplate#1471] opened 2020-11-24 18:52 UTC
# Two-factor Authentication not working with PGSQL:

- I am trying to run Boiler Template using PostgreSQL as database. Everything is installed correctly without errors but when I try to enter the Dashboard as administrator it shows me the following error:

**Illuminate \ Database \ QueryException
http://127.0.0.1:8000/account/2fa/enable
C: \ Users \ Myuser \ Desktop \ projects \ Boilertemplate \ vendor \ laravel \ framework \ src \ Illuminate \ Database \ Connection.php: 671**

It should be noted that all migrations and seeders were successful.

Please Help....

**Comment by bryanrscott** [comment] 2020-11-25 08:25
I have the same issue.   The issue is with the dependancy not with laravel/boilerplate
https://github.com/DarkGhostHunter/Laraguard/issues/43

**Comment by rappasoft** [comment] 2020-11-27 16:19
This is a problem with the package itself, here's the suggested fix in that comment thread: https://github.com/laravel/framework/issues/10847#issuecomment-155012494 

This will be fixed in the next major release (hopefully) if I decide to switch to fortify.

**Closed by rappasoft** 2020-11-27 16:19 UTC

**Comment by shinshadows** [comment] 2020-11-30 15:32
Thanks, im gonna checkit out in order to find the solution,
